version: '3.4'
services:
  mysql:
    container_name: wpphr_mysql
    image: 'mysql:latest'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: unless-stopped
    volumes:
      - 'DB:/var/lib/mysql'
      - './mysql/my.cnf:/etc/mysql/my.cnf'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10  
    networks:
      - phraseanet


volumes: 
  DB: null                  