version: '3.4'
services:
  mysql:
    container_name: mysql
    image: 'mysql:latest'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: unless-stopped
    volumes:
      - 'DB:/var/lib/mysql'
      - './mysql/my.cnf:/etc/mysql/my.cnf'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10  
  gateway:
    container_name: gateway
    image: 'nginx:1.17.4-alpine'
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - 8080:80
    volumes:
      - WPDATA:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    
  wordpress:
    container_name: wordpress
    build:
      context: .
    depends_on:
      - mysql
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      PHRASEANET_BO_URL: ${PHRASEANET_BO_URL}
      PHRASEANET_BO_TOKEN: ${PHRASEANET_BO_TOKEN}
      PHRASEANET_BO_CLIENT_ID: ${PHRASEANET_BO_CLIENT_ID}
      PHRASEANET_BO_SECRET: ${PHRASEANET_BO_SECRET}
      SITE_TITLE: ${SITE_TITLE}
      WP_ADMIN_USERNAME: ${WP_ADMIN_USERNAME}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      PHRASEANET_PLUGIN_INSTALL: ${PHRASEANET_PLUGIN_INSTALL}
      MODE: 'production'
    volumes:
      - WPDATA:/var/www/html

   
volumes:
  DB: null
  WPDATA: null